apiVersion: apps/v1
kind: Deployment
metadata:
  name: refty-image-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refty
  template:
    metadata:
      labels:
        app: refty
    spec:
      containers:
        - name: refty-api
          image: your-dockerhub-user/refty-image-updater:latest
          ports:
            - containerPort: 3001
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: token
            - name: GITHUB_USERNAME
              value: "your-username"
            - name: PORT
              value: "3001"
