apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-version-deployment
  labels:
    app: update-version
spec:
  replicas: 2
  selector:
    matchLabels:
      app: update-version
  template:
    metadata:
      labels:
        app: update-version
    spec:
      containers:
        - name: update-version-container
          image: my-tag:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
